version: '2.1'

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      XDEBUG_HOST: ${XDEBUG_HOST}
  
  gulp:
    command: ["/var/www/html/node_modules/.bin/gulp", 'watch']
    extends:
      file: docker-compose.base.yml
      service: node
    volumes:
      - ./:/var/www/html
  
  mailhog:
    image: mailhog/mailhog:latest
    ports:
        - "8025:8025"
    networks:
    - sdnet

  mysql:
    extends:
        file: docker-compose.base.yml
        service: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"

  browsersync:
    image: ustwo/browser-sync:latest
    command: start --proxy "REPLACE_THIS_WITH_FQDN" --files "public/css/*.css"
    volumes:
      - ./:/source
    ports:
      - "3000:3000"
      - "3001:3001"

  node:
    extends:
      file: docker-compose.base.yml
      service: node
networks:
  sdnet:
    driver: "bridge"
volumes:
  mysql_data:
    driver: "local"