version: '2.1'

services:

  php:
    extends:
      file: docker-compose.base.yml
      service: php
    volumes:
      - '/composer_cache:/composer_cache'

  composer:
    extends:
      file: docker-compose.base.yml
      service: php
    command: ['composer']

  yarn:
    extends:
      file: docker-compose.base.yml
      service: node
    volumes:
      - '/yarn_cache:/yarn_cache'

  gulp:
    extends:
      file: docker-compose.base.yml
      service: node

networks:
  sdnet:
    driver: "bridge"