version: '2.1'

services:

  php:
    extends:
      file: docker-compose.base.yml
      service: php
    volumes:
      - '/composer_cache:/composer_cache'
      - '/ssh:/ssh'

  node:
    extends:
      file: docker-compose.base.yml
      service: node
    volumes:
      - '/yarn_cache:/yarn_cache'

networks:
  sdnet:
    driver: "bridge"
