version: '2.1'

services:

  php:
    build:
        context: ./docker/php
        dockerfile: Dockerfile
    image: wearejust/php-fpm:7.1-wkhtmltoimage
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - sdnet

  node:
    image: wearejust/node:1.0.1
    working_dir: /var/www/html
    networks:
      - sdnet 
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sdnet
