version: '2.1'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: wearejust/app
    networks:
    - sdnet

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: wearejust/mysql
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - sdnet

  mailhog:
    build:
      context: ./docker/mailhog
      dockerfile: Dockerfile
    image: wearejust/mailhog
    ports:
        - "8025:8025"
    networks:
    - sdnet

  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
    image: wearejust/elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/config
    networks:
    - sdnet 

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: wearejust/node
    volumes:
      - ./:/var/www/html
    networks:
    - sdnet