version: '2.1'

services:

  redis:
    image: redis:4
    ports:
      - "6379:6379"
    networks:
      - sdnet

  app:
    image: wearejust/nginx:2.0.2
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on: 
      - php
    networks:
      - sdnet

  php:
    extends:
      file: docker-compose.base.yml
      service: php
    volumes:
      - ${HOME}/.composer:/composer_cache

  node:
    extends:
      file: docker-compose.base.yml
      service: node
    volumes:
        - ${HOME}/.yarn:/yarn_cache

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
        - "8025:8025"
    networks:
      - sdnet
    logging:
      driver: none

  mysql:
    extends:
        file: docker-compose.base.yml
        service: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "website"
      MYSQL_USER: "website"
      MYSQL_PASSWORD: "secret"

networks:
  sdnet:
    driver: "bridge"

volumes:
  mysql_data:
    driver: "local"
