version: '2.1'

services:

  php:
    image: wearejust/php-fpm:7.1
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - sdnet

  node:
    image: wearejust/node:1.0
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - sdnet 

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sdnet
