version: '2.1'

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    volumes:
    - './:/var/www/html'
    - '/composer_cache:/composer_cache'

  yarn:
    extends:
      file: docker-compose.base.yml
      service: node

  gulp:
    extends:
      file: docker-compose.base.yml
      service: node

  node:
    extends:
      file: docker-compose.base.yml
      service: node

networks:
  sdnet:
    driver: "bridge"
    
volumes:
  mysql_data:
    driver: "local"
