version: '2.1'

services:
  app:
    image: wearejust/nginx-php:1.0
    networks:
    - sdnet

  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - sdnet

  mailhog:
    image: mailhog/mailhog:latest
    networks:
    - sdnet

  elasticsearch:
    image: elasticsearch:5.1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/config
    networks:
    - sdnet 

  node:
    image: wearejust/node:1.0
    volumes:
      - ./:/var/www/html
    networks:
    - sdnet