version: '2.1'

services:

  composer:
    extends:
      file: docker-compose.base.yml
      service: composer
    volumes:
      - '/composer_cache:/composer_cache'

  php:
    extends:
      file: docker-compose.base.yml
      service: php

  yarn:
    extends:
      file: docker-compose.base.yml
      service: node

  gulp:
    extends:
      file: docker-compose.base.yml
      service: node

  node:
    extends:
      file: docker-compose.base.yml
      service: node
      
networks:
  sdnet:
    driver: "bridge"
    
volumes:
  mysql_data:
    driver: "local"